name: MyFileBrowser
options:
  bundleIdPrefix: com.example

configs:
  Debug:
    buildSettings:
      SWIFT_OPTIMIZATION_LEVEL: '-Onone'
  Release:
    buildSettings:
      SWIFT_OPTIMIZATION_LEVEL: '-Owholemodule'

targets:
  MyFileBrowser:
    type: application
    platform: iOS
    sources:
      - AppDelegate.swift
      - ViewController.swift
      - FileBrowser.swift
      - LoginViewController.swift
      - TextViewController.swift
    resources:
      - Assets.xcassets
      - Base.lproj
    dependencies: []
    settings:
      base:
        deploymentTarget:
          iOS: '14.0'
    scheme:
      name: MyFileBrowser
      testTargets: []
