name: MyFileBrowser
options:
  bundleIdPrefix: com.mycompany
  deploymentTarget:
    iOS: '15.0'  # Actualiza aquí a iOS 15.0
targets:
  MyFileBrowser:
    type: application
    platform: iOS
    sources: [MyFileBrowser/Sources]
    resources: [MyFileBrowser/Resources]
