name: MyFileBrowser
options:
  bundleIdPrefix: com.myfilebrowser
targets:
  MyFileBrowser:
    type: application
    platform: iOS
    deploymentTarget: "11.0"
    sources:
      - path: .
        includes:
          - "*.swift"
    resources:
      - path: Assets.xcassets
      - path: Base.lproj
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1,2 # iPhone y iPad
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: ""
        PROVISIONING_PROFILE_SPECIFIER: ""
