name: MyFileBrowser
options:
  bundleIdPrefix: com.example

configs:
  Debug:
    buildSettings:
      SWIFT_OPTIMIZATION_LEVEL: '-Onone'
  Release:
    buildSettings:
      SWIFT_OPTIMIZATION_LEVEL: '-Owholemodule'

targets:
  MyFileBrowser:
    type: application
    platform: iOS
    sources: [MyFileBrowser/Sources]
    resources: [MyFileBrowser/Resources]
    dependencies: []
    settings:
      base:
        deploymentTarget:
          iOS: '15.0'
    scheme:
      name: MyFileBrowser
      testTargets: []
