name: Build iOS App
on:
  push:
    branches:
      - main  # O la rama que desees usar
  pull_request:
    branches:
      - main  # O la rama que desees usar

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      # Paso 1: Checkout del c贸digo
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Paso 2: Configurar la versi贸n de Xcode
      - name: Set up Xcode
        uses: apple/actions/setup-xcode@v2
        with:
          xcode-version: '15.0'  # Configura la versi贸n de Xcode adecuada
      
      # Paso 3: Instalar dependencias con CocoaPods (si las tienes)
      - name: Install dependencies
        run: |
          gem install cocoapods
          pod install
      
      # Paso 4: Ejecutar la compilaci贸n para iOS 15.0
      - name: Build the project
        run: |
          xcodebuild -project MyFileBrowser/MyFileBrowser.xcodeproj \
            -scheme MyFileBrowser \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=15.0' \
            clean build
